spring:
  datasource:
    hikari:
      maximum-pool-size: 4   # 최대 커넥션 수
      minimum-idle: 2         # 최소 유휴 커넥션 수
      idle-timeout: 600000    # 유휴 커넥션 타임아웃 (밀리초 단위)
      max-lifetime: 1800000   # 최대 커넥션 생명주기 (밀리초 단위)
