server:
  port: 8081
spring:
  profiles:
    active: local
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ap-northeast-2
  s3:
    region: ap-northeast-2
    bucket:
      original: mini-shopping-images-origin
      thumbnail: mini-shopping-images-thumbnail
  sqs:
    queue:
      image-processed: https://sqs.ap-northeast-2.amazonaws.com/663530037219/mini-shopping-image-processed

